project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Hanna Chang"
  navbar:
    text: "Home"
    left:
      - text: "Projects"
        href: projects.html
      - text: "Blog"
        href: posts.qmd
          
about:
  id: intro-heading
  template: solana
  image: profile.jpeg
  links:
    - icon: github
      href: https://github.com/hanna1me
    - icon: linkedin
      href: https://www.linkedin.com/in/hannachang03/
        
page-footer:
    left: |
      &copy; Hanna Chang, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

